#!/bin/bash
if [[ "$#" -lt 1 ]]; then
  echo "Usage: delete <resource> [<id>]";
  exit 1
fi

resource=$1

if [[ "$#" -ge 2 ]]; then
  resourceId=$2
fi

cmd="curl \
  -w '\\nStatus: %{http_code}\\nHeaders:\\n%{header_json}\\n' \
  -X DELETE \
  http://localhost:3000/api/$resource/$resourceId"

eval $cmd
