#!/bin/bash
script_path=$(realpath $0)
script_dir=$(dirname $script_path);
source $script_dir/../.env 2> /dev/null

if [[ "$#" -lt 1 ]]; then
  echo "Usage: get <resource> [<id>]";
  exit 1
fi

resource=$1

if [[ "$#" -ge 2 ]]; then
  resourceId=$2
fi

cmd="curl \
  -w '\\nStatus: %{http_code}\\nHeaders:\\n%{header_json}\\n' \
  -X GET \
  http://localhost:3000/api/$resource/$resourceId"

eval $cmd
