#!/bin/bash
if [[ "$#" -lt 3 ]]; then
  echo "Usage: patch <resource> <id> '<data>'";
  exit 1
fi

resource=$1
resourceId=$2
shift 2
data="'$*'"

cmd="curl \
  -w '\\nStatus: %{http_code}\\nHeaders:\\n%{header_json}\\n' \
  -X PATCH \
  --header 'Content-Type: application/json' \
  --data $data \
  http://localhost:3000/api/$resource/$resourceId"

eval $cmd
