#!/bin/bash
script_path=$(realpath $0)
script_dir=$(dirname $script_path);
source $script_dir/../.env 2> /dev/null

port=${SERVER_PORT:-3000}

if [[ "$#" -lt 3 ]]; then
  echo "Usage: put <resource> <id> '<data>'";
  exit 1
fi

resource=$1
resourceId=$2
shift 2
data="'$*'"

cmd="curl \
  -w '\\nStatus: %{http_code}\\nHeaders:\\n%{header_json}\\n' \
  -X PUT \
  --header 'Content-Type: application/json' \
  --data $data \
  http://localhost:${port}/api/$resource/$resourceId"

eval $cmd
